import "@/styles/globals.css";
import "@/styles/prosemirror.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";

import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";
import AppProvider from "@/context/app-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AppProvider>
          <ThemeProvider>
            <NextTopLoader />
            {children}
            <Toaster
              position="bottom-right"
              toastOptions={{
                className: "bg-foreground/75 text-background capitalize",
              }}
            />
          </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}
